### ISSUE TITLE
Issue with'outline modification' function in preprocessing

### ISSUE THREAD

**Issue by Zhe-Cai** [majroy/pyCM#11]
If performes Abaqus-based preprocessing using pyCM, the *.dxf file will be needed in outline modification function by click 'update' and select the output directory. However, the *.dxf file will always be written into 'pyCM'( which contains all the *.py files) folder rather than the directory you select when click 'update' button. I suggest that user select the output directory by default( the pyCM folder) to avoid further issues.

**Comment by majroy** [comment]
Should be addressed in 1.1.7
On load of the mat file, the desired behaviour is that the dxf path proves to be valid. If it is not, then the dxf file will be extracted from the mat file and written to the same path as the mat file, with the prefix preserved.
