### ISSUE TITLE
Issue with 'generate mesh' function in preprocessing 

### ISSUE THREAD

**Issue by Zhe-Cai** [majroy/pyCM#12]
When use Abaqus to generte mesh, after click 'Execute' button, pyCM will request an output directory for .py file. If user select another directory rather than the 'pyCM' folder( which contains all the pyCM program) , the program will write a .inp file into that new directory, which subsecquently cause an error and result in a crash. The program will try to find the .inp file in 'pyCM' folder rather the directory assigned by the user.

To carry on the mesh generation, user should copy the .inp file into pyCM folder after carsh or select the output directory by default( the pyCM folder) to avoid further issues.

**Comment by majroy** [comment]
Should be addressed in 1.1.7
On load of the mat file, the desired behaviour is that the inp path proves to be valid. If it is not, then the inp file will be extracted from the mat file and written to the same path as the mat file, with the prefix preserved.
