### ISSUE TITLE
Hull failed, try increasing cutoff

### ISSUE THREAD

**Issue by MaximilianSP** [majroy/pyCM#16]
Hi Mat, 
I am using the newest pyCM version and trying to generate the outline from the laser scanner/ confocal data. So far I have tried to play with the threshold but nothing is happening. 

![image](https://user-images.githubusercontent.com/45238826/65255430-2d6a4b80-dafe-11e9-86c5-1c5bd57d2324.png)

I increase the cutoff as much as possible but it doesn't help. In this case, I am working on a point cloud acquired from a rectangular surface.

Do you have some sort of best practice when it comes to the threshold? 

Thank you very much!

**Comment by MaximilianSP** [comment]
Same issue with this geometry:
![image](https://user-images.githubusercontent.com/45238826/65257001-c9955200-db00-11e9-998a-c6bdea7494e6.png)

**Comment by majroy** [comment]
Increase the threshold to something quite large. Try 10. Then work downwards. I appologise, the threshold argument isn't the most transparent.

**Comment by MaximilianSP** [comment]
Ok, I am working on it and will report.

**Comment by majroy** [comment]
I'm going to close this hoping that it did work in the end.
