### ISSUE TITLE
Averaging failed

### ISSUE THREAD

**Issue by RafaelBrm** [majroy/pyCM#17]
Hi Matthew,

I'm using the newst pyCM Version and trying to average the two point Clouds. I get different error messages with the point clouds, see the following Pictures. I'm working on a point Cloud acquired from a rectangular surface. 

![Error_average](https://user-images.githubusercontent.com/57218175/67940967-f4c99180-fbd4-11e9-9169-63eb49abc24b.png)
![error_average_IPA_ohne_aligned](https://user-images.githubusercontent.com/57218175/67940968-f5622800-fbd4-11e9-8123-e9b375ac4835.png)
![Error_average_IPA](https://user-images.githubusercontent.com/57218175/67940969-f5622800-fbd4-11e9-98d0-f285e15caee2.png)

If you have any tips, please let me know!
Thank you very much!

**Comment by majroy** [comment]
Hi RafaelBrm, that looks like you’ve got too many points; how many points are in the point clouds that you’re trying to average?

**Comment by RafaelBrm** [comment]
For the first Error it was about 150.000 points per file
For the second and the third it was about 1.500.000 points per file

**Comment by majroy** [comment]
I'm going to have to defer to this being machine specific - we commonly process point clouds with 500k counts - so all I can say is that 1.5M points is excessive, the 150k should work. I suggest that you try reducing your counts.
