### ISSUE TITLE
pyCM crashing. Please help!

### ISSUE THREAD

**Issue by damjamx** [majroy/pyCM#18]
Hi Mat,
I am using pyCM. I was able to install successfully but noticed that the program won't open if I try to open through "main'“ but opened through the "main.cpython-37" in the _pycache_ folder. I was able to run an example successfully immediately after installation and I saved the file. However, since the time I closed the program till now, every time I try to load point clouds or the saved example it keeps crashing and give an error log as shown below. I have also attached the Python37 folder showing the packages installed. Please kindly advise. Thank you. I look forward to hearing from you.

![2](https://user-images.githubusercontent.com/46848851/73666911-60018480-4658-11ea-8a8c-4784a3c1e5cb.PNG)
![3](https://user-images.githubusercontent.com/46848851/73666922-64c63880-4658-11ea-9670-39aba7601d1e.PNG)

![1](https://user-images.githubusercontent.com/46848851/73666874-50823b80-4658-11ea-8bc7-80a212cf3992.PNG)

**Comment by majroy** [comment]
It shouldn't crash because of VTK errors. Unless there's an error reported back by the interpreter, I can't help you. Additionally, 'main' is merely a helper function. If you have installed pyCM via pip, then you should be able to run each of the steps as independent scripts, or from interactive python as described in the documentation.

**Comment by damjamx** [comment]
Thank you very much for your response majroy. I was able to solve that problem but now I have the following log when I tried to load a point cloud from a laser scanner. The point cloud has been sampled and reduced. I can attach the files on request. Please kindly advise. Kind regards. Damjamx. 

![image](https://user-images.githubusercontent.com/46848851/82082602-28659800-969d-11ea-8f30-fa4cd626cd1b.png)

**Comment by damjamx** [comment]
Problem solved. Thank you.
