### ISSUE TITLE
Postprocessing Tab Issue

### ISSUE THREAD

**Issue by IoannisPantelis** [majroy/pyCM#19]
Greetings.

At the last step of my analysis (Postprocessing tab) - when I am trying to change the max and min contour values to visualise the results -  the GUI crashes after I click the ''Update'' button. 

![errorr](https://user-images.githubusercontent.com/47006188/74660765-b14c6080-518e-11ea-85c8-c3273377acb4.PNG)

Here's the error: 
![error in postprocessing tab pycm](https://user-images.githubusercontent.com/47006188/74660155-7f86ca00-518d-11ea-9222-cc98b1ccf017.PNG)

I tried to replace the commas with dots, but it didn't work.

PyCM is immediately converting 650.00 (with a dot) to 650,00(with a comma).

Same problem happens when trying to plot a stress profile. 

Here's the error: 
![error in postprocessing tab plot pyCM](https://user-images.githubusercontent.com/47006188/74660565-413dda80-518e-11ea-81db-12c784dd3ad4.PNG)

I would appreciate any feedback/potential solution to this issue. 

Thank you in advance

**Comment by majroy** [comment]
I trust that this is the only point which throws this error - change your OS to English while I patch this.

**Comment by majroy** [comment]
Addressed in the latest version.
