### ISSUE TITLE
GUI got crashed at alignment and averaging step

### ISSUE THREAD

**Issue by kartheek848** [majroy/pyCM#20]
Hii, when I am performing mirroring step(about zx), program is getting crashed without giving any error. I am using windows 10 laptop, with pyCM installed using pip package manager. 
![error](https://user-images.githubusercontent.com/61617407/75612589-03a45e80-5b4b-11ea-86b3-c74df877aefe.PNG)

When I press Zx the GUI is not responding and gets closed.

**Comment by majroy** [comment]
I'm going to have to close this on the basis that I cannot replicate.
