### ISSUE TITLE
Divergence between the fit surface at fit_surface and preprocess modules

### ISSUE THREAD

**Issue by lucapbelotti** [majroy/pyCM#24]
I noticed that when I fit a surface (left image) and use it to impose the displacement boundary conditions, a different fit surface is being enforced. Additionally, when reloading a previously fit .mat file, the surface also is different than initially fit.

![fit_surface](https://user-images.githubusercontent.com/41550623/96094209-5f024180-0ecd-11eb-905e-a9e0689be7c0.jpg)
![preprocess](https://user-images.githubusercontent.com/41550623/96094212-5f9ad800-0ecd-11eb-8e75-0e276385c06f.jpg)

**Comment by Zhe-Cai** [comment]
Hi lucapbelotti,
We have noticed this issue and released a new post: pyCM-1.1.8.post3 to fix this. The issue was resulted from a typo in fit_surface.py, the fitted spline was assigned with wrong index when writing to 'mat' file, which caused the 'divergence' you mentioned above.

**Comment by majroy** [comment]
@lucapbelotti, please report back if this sorts things out for you, and I'll close the issue.

**Comment by lucapbelotti** [comment]
Thank you very much for sorting this issue out. Things seem to be working fine
