### ISSUE TITLE
Preprocessing module couldn't read variables from file 

### ISSUE THREAD

**Issue by Jagatheesh003** [majroy/pyCM#28]
Error:
1) only integer scalar arrays can be converted to a scalar index
     pyCM pre couldn't read variables from file; the error was: only integer scalar arrays can be converted to a scalar index

2) get_limits() and get_axis() not defined. Missing function

![image](https://user-images.githubusercontent.com/97026875/152210891-c407c8c8-af96-4fac-af03-3f4e9dd573e4.png)
![image](https://user-images.githubusercontent.com/97026875/152211013-07db415f-8821-434b-8329-e4b0baeeba1d.png)

**Comment by majroy** [comment]
Can you confirm that you've implemented the fix described in [Issue 27](https://github.com/majroy/pyCM/issues/27)?

**Comment by majroy** [comment]
Closing issue in light of new version and lack of feedback.
