### ISSUE TITLE
Issues when dealing with semi-circular data

### ISSUE THREAD

**Issue by CKHofHIT** [majroy/pyCM#31]
I am currently working with pyCM and have encountered a few questions and challenges during my implementation. I would be grateful if you could spare some time to address these queries and provide guidance. 
I am using a set of data in the shape of a semi-circle (as shown in the figure below) for contour analysis. When I load the data in the pre-processing tab, an error message will appear: "ValueError: x and y arrays must be equal in length along interpolation axis."
I am using version 2.0.0post1. Could you please help me understand what might be causing this error? Thank you.
Looking forward to your response.
![image](https://github.com/majroy/pyCM/assets/100893098/40ee045c-a470-4c59-a0c1-303e90d3a163)
![image](https://github.com/majroy/pyCM/assets/100893098/21681270-7d57-453c-bc59-6a20c01af83f)

**Comment by CKHofHIT** [comment]
I am using the post1 version indeed, here is my pycm file
[pyCM-2.0.0.post1.tar.gz](https://github.com/majroy/pyCM/files/11878834/pyCM-2.0.0.post1.tar.gz)

**Comment by CKHofHIT** [comment]
Ok here is the .pycm file of my data
[semi-circular.zip](https://github.com/majroy/pyCM/files/11881706/semi-circular.zip)

**Comment by CKHofHIT** [comment]
Ok, I have uploaded a .pycm file of my data



在 2023-06-27 19:00:49，"Matthew Roy" ***@***.***> 写道：

Your attachment is the source for pyCM, please post your pyCM datafile, that is, the one which contains the data with a .pyCM extension which is causing an issue.

**Comment by majroy** [comment]
I haven't been able to replicate your issue with the file you've given me. It seems as though you are using an older version of Python, and perhaps an even older version of SciPy. The base level that I can test to is Python 3.9 with SciPy 1.8.0.
![image](https://github.com/majroy/pyCM/assets/4645426/2dd98ffe-f8e7-41a2-b28f-787d3641afd8)

**Comment by CKHofHIT** [comment]
alright, thank you very much. It seems to be a problem with my software version, I will try it with Python 3.9 with SciPy 1.8.0.

**Comment by CKHofHIT** [comment]
My previous python version was 3.85, I used Python 3.9 to fix the problem, you can now close this issue, thank you very much!



---- Replied Message ----
| From | Matthew ***@***.***> |
| Date | 06/28/2023 19:30 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [majroy/pyCM] Issues when dealing with semi-circular data (Issue #31) |

I haven't been able to replicate your issue with the file you've given me. It seems as though you are using an older version of Python, and perhaps an even older version of SciPy. The base level that I can test to is Python 3.9 with SciPy 1.8.0.
