### ISSUE TITLE
GUI crashes during surface fitting

### ISSUE THREAD

**Issue by mdomogala** [majroy/pyCM#32]
Dear Matthew,

I am trying to fit a surface for both sets of sample data provided. When using the GUI, the spline fitting either fails, if the spacing is small or crashes when increased or using the pre-selected size. I am working with version 2.0.0.post1.

The terminal gives me an Attribute Error as shown in the snip below.
![image](https://github.com/majroy/pyCM/assets/137737505/01abf666-059e-493f-a9e4-8ec748570f7c)

I have attached both pyCM files for your information, hope you can work with the provided information. 

Thanks in advance,
Markus.

[SampleData.zip](https://github.com/majroy/pyCM/files/11875227/SampleData.zip)

**Comment by mdomogala** [comment]
Thanks a lot for the response and the suggested change of code, that did the trick for me using SciPy 1.11.0. 

Best regards,

Markus

**Comment by majroy** [comment]
Fixed now with v2.0.0post2, compatible with SciPy 1.11.

**Comment by majroy** [comment]
Fixed now with v2.0.0post2, compatible with SciPy 1.11.
