### ISSUE TITLE
Install issue of PyCM on laptop

### ISSUE THREAD

**Issue by didiyang1** [majroy/pyCM#34]
![python mistake](https://github.com/majroy/pyCM/assets/125886868/36f9a38f-bd67-4f1a-8605-efabc9158d34)

When I install the latest version of PyCM in my laptop, there show an issue like the screenshot above.

**Comment by majroy** [comment]
Addressed wtih post3; verified with Python 3.11 running Scipy 1.12.0. Please verify.

**Comment by majroy** [comment]
Verified as resolved.
