### ISSUE TITLE
Postprocessor feature request for C3D10 tetrahedral elements quadrature

### ISSUE THREAD

**Issue by NikStoyanov** [majroy/pyCM#7]
Add a feature to the postprocessor to support quadrature for ten-node tetrahedral elements (C3D10)

**Comment by majroy** [comment]
Would it be easier to do for C3D4? I can change the meshing scripts . . .

**Comment by majroy** [comment]
Any luck? You can hand off where you got up to, if you'd like.

**Comment by NikStoyanov** [comment]
I have just cherry picked the old commits which modify the C3D4 elements to C3D10 in #22 

We need to go over some integration testing to see if it matches in Abaqus and Calculix.

**Comment by majroy** [comment]
Version 2 supports C3D10 from both preprocessing as well as in post processing.
