### ISSUE TITLE
Outline file 

### ISSUE THREAD

**Issue by MaximilianSP** [majroy/pyCM#9]
Hi,

I am currently working on a point cloud generated by a laser based CMM and I have issues “creating” my outline. One difficulty is the extraction of the outline and once I have a file, I have the problem that my points get connected in the following way: 

 
![outline_issue](https://user-images.githubusercontent.com/45238826/53028567-6ad30180-3467-11e9-97fc-f716fbb78446.PNG)

It seems the outline points are connected according to their occurrence in the text file. The subsequent analysis steps fail. Is the only way for me to overcome this issue by extracting my outline from the Point Cloud similar to what a CMM would do? Thank you in advance for your help.

**Comment by majroy** [comment]
Hi - UoM has code that works with non-contact profilometers. However, I do not have a license for this code. You will need to have an ordered outline/hull of points that either goes clockwise or counterclockwise.

The algorithm for our code is: 
1) Tessellate (Delaunay will do)
2) Sort based on normals of the triangles. This will identify points on the 'cusp' of the edge (edge candidates). 
3) On the xy plane, solve for the convex hull of the edge candidates, which will give you an ordered list of points. 
4) If you have areas which are concave, take the longest segments of the hull, and then find a point from the edge candidates that are closest, repeating until you come close to whatever your mean point spacing is.

I am working through getting in support for self-restraint features, if you make your profilometer data available, then I can attempt to do this next, unless you get to it, of course ;)

**Comment by MaximilianSP** [comment]
Hi, 
Thank you for the input! I will try to write a code as I will sooner or later be again confronted to the same issue. Nonetheless, I highly appreciate your offer of having a look at the data : ) Is it ok via E-Mail?

**Comment by majroy** [comment]
I have started on this - can you please let me know if your data is regularly spaced on a grid or not? Significant savings can be made by converting it to an image (and then perform a kernel search), which is only really possible if it's regularly spaced.

**Comment by MaximilianSP** [comment]
I have used the voxel downsampling function of open 3D. It is using a regular voxel grid and averages all points in a given voxel size.

**Comment by majroy** [comment]
Hi - the just releasesd v1.1.8 *should* do what you need it to do in point_cloud. Look at the documentation, it covers what I described above.

**Comment by MaximilianSP** [comment]
Brilliant! I will try out the new version this weekend.

Von: Matthew Roy <notifications@github.com>
Gesendet: Donnerstag, 1. August 2019 18:25
An: majroy/pyCM <pyCM@noreply.github.com>
Cc: Sprengel, Maximilian <maximilian.sprengel@bam.de>; Author <author@noreply.github.com>
Betreff: Re: [majroy/pyCM] Outline file (#9)


Hi - the just releasesd v1.1.8 should do what you need it to do in point_cloud. Look at the documentation, it covers what I described above.
